name: Build and deploy to K8s based on folder change and runner label

# on:
#   push:
#     branches:
#       - dev
#       - staging
#       - master

on: workflow_dispatch

jobs:  
  setting-environment:
    name: setting-environment
    runs-on: ubuntu-latest
    outputs:
      environment-name: ${{ steps.get-environment.outputs.environment-name }}
    steps:
      - name: Determine Environment
        id: get-environment
        uses: tj-actions/changed-files@v14.1
        with:
          files: |
            my-file.txt
  Deploy-to-dev:
    runs-on: ubuntu-latest
#     runs-on: [ dev ]
    needs: setting-environment
    name: Deploy to dev
    environment: dev
    if: ${{ needs.setting-environment.outputs.environment-name != 'none' }}
    steps:
      - uses: tj-actions/changed-files@v14.1
        with:
          files: |
            dev
      - uses: ministryofjustice/setup-git-crypt@main
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - name: Deploying to Dev environment
        run: |
          export KUBECONFIG="/etc/kubeconfig"
          kubectl apply -f ./dev
  Deploy-to-prod:
    runs-on: ubuntu-latest
  #   runs-on: [ prod ]
    needs: setting-environment
    name: Deploy to prod
    environment: prod
    if: ${{ needs.setting-environment.outputs.environment-name != 'none' }}
    steps:
      - uses: tj-actions/changed-files@v14.1
        with:
          files: |
            prod
      - uses: ministryofjustice/setup-git-crypt@main
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - name: Deploying to prod environment
        run: |
          export KUBECONFIG="/etc/kubeconfig"
          kubectl apply -f ./dev
